FROM centos:centos8
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
    dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
RUN dnf install -y wget bzip2 unzip file which
RUN dnf module install -y php:remi-7.4
RUN dnf install -y php-devel php-pdo php-mysqlnd php-zip php-gd

COPY composer.sh .
RUN sh composer.sh && \
    mv composer.phar /usr/local/bin/composer
